### PR TITLE
Update naming-conventions.md

### PR DESCRIPTION
**Pull request by teddybradford**

### CODE REVIEW

**Comment by MoOx** [comment]
I don't think this make sense since this dash is optional (according to the fact that you might use a size modifier or not).

**Comment by simonsmith** [comment]
Yeah, there are utilities such as `u-size1of2` so this would imply it was `u--size1of2`

**Comment by teddybradford** [comment]
Ah, I see. In that case, would this be better? `u-[sm-|md-|lg-]<utilityName>`

**Comment by simonsmith** [comment]
That would be correct yeah.

**Comment by teddybradford** [comment]
#100

**Pull request closed without merging**
